name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
   build:
    uses: nateraw/huggingface-sync-action/.github/workflows/sync_with_hf_hub.yml@main
    with:
      github_repo_id: nateraw/vsc2022-dataset-visualizer
      huggingface_repo_id: nateraw/vsc2022-dataset-visualizer
      repo_type: space
      space_sdk: streamlit
    secrets:
      hf_token: ${{ secrets.HF_TOKEN }}